### ISSUE TITLE
NullPointerException running export

### ISSUE THREAD

**Issue by timwhitlock** [hamsterksu/AndroidLangTool#5]
Hello, 
I get an error running `java -jar LangTool.jar -e MyApp file.csv`:

    Exception in thread "main" java.lang.NullPointerException
	  at com.gdubina.tool.langutil.ToolExport.export(ToolExport.java:73)
	  at com.gdubina.tool.langutil.ToolExport.run(ToolExport.java:68)
 	  at com.gdubina.tool.langutil.ToolExport.run(ToolExport.java:56)
	  at com.gdubina.tool.langutil.Tool.main(Tool.java:22)

On Mac OS X 10.9.5:

    java version "1.6.0_65"
    Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
    Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

Is this an incompatibility, or am I doing something wrong? (I'm not a Java dev)

**Comment by matrad4307** [comment]
I'm have the same problem
