### ISSUE TITLE
Not export to xls. Getting NullPointerException Error

### ISSUE THREAD

**Issue by ramkia613** [hamsterksu/AndroidLangTool#6]
Exception in thread "main" java.lang.NullPointerException
        at com.gdubina.tool.langutil.ToolExport.export(ToolExport.java:73)
        at com.gdubina.tool.langutil.ToolExport.run(ToolExport.java:68)
        at com.gdubina.tool.langutil.ToolExport.run(ToolExport.java:56)
        at com.gdubina.tool.langutil.Tool.main(Tool.java:22)

**Comment by pianetarosso** [comment]
I forked and solved the issue.

Source there: https://github.com/deltaaskii/android-lang-tool
